### ISSUE TITLE
File duplication issue

### ISSUE THREAD

**Issue by aditrademark** [asu-trans-ai-lab/grid2demand#16]
When the grid2demand code is run multiple times, the code generates duplicates of the output files instead of overwriting them. For example, the duplicates appear as zone_1.csv, zone_1_1.csv and so on. I believe we discussed this issue last week and came to the conclusion that it is tedious for the user to rename, delete and reorganize the output files. Your effort to fix this would be greatly appreciated!

**Comment by xyluo25** [comment]
Hi Aditya,
Yes, we are careful not to overwrite user-input data while generating additional fields from these input files. As you've noted in your statement, we create files named 'zone.csv', 'zone_1.csv', and 'zone_1_1.csv' specifically to prevent overwriting any existing files.
