### ISSUE TITLE
Error: invalid continuation byte

### ISSUE THREAD

**Issue by aditrademark** [asu-trans-ai-lab/grid2demand#17]
I have noticed that running the following line causes the code to throw an error.

Step 1: Load node and poi data from input directory
node_dict, poi_dict = gd.load_network.values()

The error thrown is as follows.
![image_2023-10-31_205817454](https://github.com/asu-trans-ai-lab/grid2demand/assets/141453186/2c2078c1-369f-4907-8244-b7676e2744d6)

I have replicated this issue under different conditions and I have come to the conclusion that the problem is caused by poi.csv file generated from osm2gmns. It would seem that the first column "name" in poi.csv causes this issue and deleting this column "fixes" the issue. The image below should give some context.

![WhatsApp Image 2023-10-22 at 22 22 17](https://github.com/asu-trans-ai-lab/grid2demand/assets/141453186/cb10bbad-5573-4427-b0f2-411025641add)

Please let me know if my conclusion of the source of the problem is incorrect. Thank you.

**Comment by xyluo25** [comment]
Hi Aditya, 
Thank you and our updated version has resolved it.
