### ISSUE TITLE
KeyError: 0

### ISSUE THREAD

**Issue by aditrademark** [asu-trans-ai-lab/grid2demand#18]
I have noticed that running the following code does not work when the node_id (in the node.csv file generated by osm2gmns) starts with anything other than 0.

Step 2: Generate zone dictionary from node dictionary by specifying number of x blocks and y blocks
zone_dict = gd.net2zone(node_dict, num_x_blocks=25, num_y_blocks=25)

The error is shown in the image below.
![image_2023-10-31_210650318](https://github.com/asu-trans-ai-lab/grid2demand/assets/141453186/d8dca3b8-6c52-4b49-b532-c9e05fa67cb2)

Your efforts to fix this issue would be greatly appreciated. Thank you.

**Comment by xyluo25** [comment]
Hi Adiya, 

Thank you for your feedback on this issue. Are you still experiencing the problem? I believe our updated version has resolved it. For further details, please contact xluo70@asu.edu.
