### ISSUE TITLE
Is it possible given only the traffic flow from each cell of grid estimate the origin destination demand?

### ISSUE THREAD

**Issue by WilliamZhao1999Disit** [asu-trans-ai-lab/grid2demand#26]
I have the traffic flow of each cell of grid 8x8 a priori,
Given only the traffic flow from each cell of the grid, is it possible to estimate the origin-destination demand?

How to call the methods or functions to obtain the ODs?

**Comment by asu-trans-ai-lab** [comment]
Please check out: OD estimation module:  Taehooie/CGODME at
fix/loss_expression_with_simplification (github.com)
<https://github.com/Taehooie/CGODME/tree/fix/loss_expression_with_simplification>
--
Xuesong (Simon) Zhou
School of Sustainable Engineering and the Built Environment
Arizona State University
Email: ***@***.***

**Comment by WilliamZhao1999Disit** [comment]
ok thanks
