### ISSUE TITLE
zone data are listed twice in zon.csv

### ISSUE THREAD

**Issue by asu-trans-ai-lab** [asu-trans-ai-lab/grid2demand#3]
The zone numbers are copied twice in zone.csv. 
https://github.com/asu-trans-ai-lab/osm_test_data_set/blob/main/test_gtfs.ipynb
![image](https://user-images.githubusercontent.com/74271152/113784281-05dfd180-96ea-11eb-9dfa-7e58a0769556.png)

**Comment by EntaiWang99** [comment]
Before rerunning the code in colab, please restart and clear all memory for the environment to solve the overwriting issue.
![image](https://user-images.githubusercontent.com/55026701/114292955-def81580-9ac4-11eb-8f38-28be1f6e56eb.png)
